### ISSUE TITLE
Transformer before Verifier

### ISSUE THREAD

**Issue by rapidfsub** [ash-project/spark#104]
**Is your feature request related to a problem? Please describe.**

I cannot run this transformer, because AshPostgres verifier halt compilation.

```
defmodule MyApp.Transformers.PreparePostgres do
  alias Spark.Dsl.Transformer
  use Spark.Dsl.Transformer

  def transform(dsl) do
    type = MyApp.Extensions.Base.Info.base_type!(dsl)

    {:ok,
     dsl
     |> Transformer.set_option([:postgres], :repo, MyApp.Repo)
     |> Transformer.set_option([:postgres], :table, type)}
  end

  def before?(_) do
    true
  end
end
```

**Describe the solution you'd like**

I want to run some transformers before verifier.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

For example

```elixir
use Spark.Extension,
  transformers_before_verify: [MyApp.Transformers.PreparePostgres]
```

**Comment by zachdaniel** [comment]
All transformers run before all verifiers already. I think whatever issue you are facing lies somewhere else. Can you describe the issue that you're seeing?

**Comment by rapidfsub** [comment]
![image](https://github.com/ash-project/spark/assets/43976328/29fa8159-24d5-4efd-aa39-41aed5dd594c)
This is dsl.ex

**Comment by rapidfsub** [comment]
I think transformers run after verifiers.

**Comment by zachdaniel** [comment]
That is called with specific transformers that are marked as `def after_compile?, do: true`, not all transformers. 

This is an old style of writing verifiers that is still supported, but regardless, normal transformers do not run after verifiers.

**Comment by rapidfsub** [comment]
Aha. Thanks. I'll debug my code again.

**Comment by rapidfsub** [comment]
I think I missunderstood something.
![image](https://github.com/ash-project/spark/assets/43976328/c289c17c-df6d-49e8-83a4-1bba19da06ae)
I thought this error was raised by verifier, but this was an option error by the code forked from nimble option.
Thank you for your help.
