### ISSUE TITLE
Remove the colon from the generated DSL docs

### ISSUE THREAD

**Issue by user20230119** [ash-project/spark#113]
**Describe the bug**
Document filenames with colons causes git to fail.

https://github.com/ash-project/ash_admin/issues/216

**To Reproduce**
On Windows, run `mix deps.get` with a github dependency that contains colons in document filename.

```
  defp deps do
    [
      {:ash_admin, github: "https://github.com/ash-project/ash_admin.git", branch: "live_view_1.0"},
```

```
mix deps.get
* Getting ash_admin (https://github.com/ash-project/ash_admin.git - live_view_1.0)
remote: Enumerating objects: 4935, done.
remote: Counting objects: 100% (1017/1017), done.
remote: Compressing objects: 100% (262/262), done.
remote: Total 4935 (delta 848), reused 853 (delta 745), pack-reused 3918 (from 1)
error: invalid path 'documentation/dsls/DSL:-AshAdmin.Domain.md'
error: invalid path 'documentation/dsls/DSL:-AshAdmin.Resource.md'
** (Mix) Command "git --git-dir=.git checkout --quiet live_view_1.0" failed
```

**Runtime**
 - Elixir version 1.17.3
 - Erlang version 27.1
 - OS Windows 10
 - Spark version

**Comment by zachdaniel** [comment]
Fixed in the latest release. This will naturally work its way into our projects over time as they update spark. I will update the specific one you are trying to clone though (ash_admin). Thanks for the report.
