### ISSUE TITLE
Dynamic extensions

### ISSUE THREAD

**Issue by jimsynz** [ash-project/spark#21]
Allow extensions to extend the DSL of _other_ extensions at specific paths.  This is required for custom strategies to actually work as intended in `ash_authentication`.

Example:

```elixir
defmodule User do
  use Ash.Resource, extensions: [AshAuthentication, MyCustomStrategy]

  authentication do
     strategies do
       my_custom_strategy()
     end
  end
end
```

**Comment by zachdaniel** [comment]
Implemented in main :)
