### ISSUE TITLE
Cannot patch top level sections.

### ISSUE THREAD

**Issue by jimsynz** [ash-project/spark#57]
**Describe the bug**
Extensions don't appear to be able to patch top level sections with new entities.

**To Reproduce**

I have made a minimal reproduction here https://github.com/jimsynz/spark_patch_top_level_section_bug

**Expected behavior**
Extensions should be able to add new entities to top level sections.

**Runtime**
 - Elixir version `1.15.5`
 - Erlang version `26.0.2`
 - OS `Darwin Eeloo.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64`
 - Spark version `1.1.24`

**Comment by zachdaniel** [comment]
Fixed in 86c9ea5c5108e7f84fc3edd5433c9ff829aeb3ca

**Comment by jimsynz** [comment]
Unfortunately it is not fixed 😭 

```
$ mix hex.info spark
Generic tooling for building DSLs

Config: {:spark, "~> 1.1"}
Locked version: 1.1.25
Releases: 1.1.25, 1.1.24, 1.1.22, 1.1.21, 1.1.20, 1.1.19, 1.1.18, 1.1.17, ...

Licenses: MIT
Links:
  GitHub: https://github.com/ash-project/spark
  
$ mix test
error: undefined function entity/1 (there is no such import)
  test/patch_top_level_section_bug_test.exs:7: PatchTopLevelSectionBugTest.PatchedDsl (module)


== Compilation error in file test/patch_top_level_section_bug_test.exs ==
** (CompileError) test/patch_top_level_section_bug_test.exs: cannot compile module PatchTopLevelSectionBugTest.PatchedDsl (errors have been logged)
    test/patch_top_level_section_bug_test.exs:4: (module)
    (elixir 1.15.0) lib/kernel/parallel_compiler.ex:484: Kernel.ParallelCompiler.require_file/2
    (elixir 1.15.0) lib/kernel/parallel_compiler.ex:379: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8
```

**Comment by zachdaniel** [comment]
I think you may need to make this change that I had to make to your repro project when testing?

diff --git a/lib/target_dsl.ex b/lib/target_dsl.ex
index d690df6..cfd4b22 100644
--- a/lib/target_dsl.ex
+++ b/lib/target_dsl.ex
@@ -1,6 +1,7 @@
 defmodule TargetDsl do
   defmodule Ext do
-    use Spark.Dsl.Extension, section: %Spark.Dsl.Section{name: :top_level, top_level?: true}
+    use Spark.Dsl.Extension,
+      sections: [%Spark.Dsl.Section{name: :top_level, top_level?: true, patchable?: true}]
   end
 
   use Spark.Dsl, default_extensions: [extensions: [Ext]]
 end
 
 
 Alternatively, you may just need to force compile the DSL module.

**Comment by jimsynz** [comment]
![dammit](https://media.giphy.com/media/Imefetl2ldDjksdV9X/giphy.gif)

https://github.com/ash-project/reactor/commit/f8e5292f3d2f1cf39acee38bcc7ba9916b3147ad
