### ISSUE TITLE
Ability to provide aliases for sections, entities and options.

### ISSUE THREAD

**Issue by jimsynz** [ash-project/spark#63]
It might be nice to be able to provide a list of aliases for entities, sections and options that will define additional macros (or maybe `defdelegate` them?).

The use case that comes to mind is everywhere there is alternative spellings for a word based on locale (eg `initialise` vs `initialize`).

**Comment by zachdaniel** [comment]
🤔 TBH I'd rather *not* provide localized options I think? I could see the value add being for deprecating old names or something like that, so you can easily say "this will be called X in the future" and not have to define both options. But like it would be strange if we had `String.capitalize` and `String.capitalise`.

**Comment by jimsynz** [comment]
![okie dokie](https://media.giphy.com/media/r3CfHW9dJStGGrPTFZ/giphy.gif)
